const actionTypes = {
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
    GET_AUTH_TOKEN_DATA_SUCCESS: 'GET_AUTH_TOKEN_DATA_SUCCESS',
    GET_AUTH_TOKEN_DATA_FAILURE: 'GET_AUTH_TOKEN_DATA_FAILURE',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    ADD_DASHBOARD_COLUMN_SUCCESS: 'ADD_DASHBOARD_COLUMN_SUCCESS',
    ADD_DASHBOARD_COLUMN_FAILURE: 'ADD_DASHBOARD_COLUMN_FAILURE',
    GET_DASHBOARD_COLUMN_SUCCESS: "GET_DASHBOARD_COLUMN_SUCCESS",
    GET_DASGBOARD_COLUMN_FAILURE: "GET_DASGBOARD_COLUMN_FAILURE",
    DELETE_DASHBOARD_COLUMN_SUCCESS: "DELETE_DASHBOARD_COLUMN_SUCCESS",
    DELETE_DASHBOARD_COLUMN_FAILURE: "DELETE_DASHBOARD_COLUMN_FAILURE"
}

export default actionTypes